### ISSUE TITLE
virus clsuting

### ISSUE THREAD

**Issue by ChaoXianSen** [mijiandui/metav#1]
Hi !
how to process virus clustering? What tools are available?

thanks a lot !

**Comment by mijiandui** [comment]
Dear ChaosXianSen,
We used support code from checkV to process virus clustering.
Thanks
Jiandui Mi

**Comment by ChaoXianSen** [comment]
![6208140a2f8be395141cbe489b7ffcd](https://github.com/mijiandui/metav/assets/26301954/5ede2f8e-acfe-43e9-a27e-bc93c95671f3)

CheckV v1.0.1: assessing the quality of metagenome-assembled viral genomes
https://bitbucket.org/berkeleylab/checkv

usage: checkv <program> [options]
programs:
    end_to_end          run full pipeline to estimate completeness, contamination, and identify closed genomes
    contamination       identify and remove host contamination on integrated proviruses
    completeness        estimate completeness for genome fragments
    complete_genomes    identify complete genomes based on terminal repeats and flanking host regions
    quality_summary     summarize results across modules
    download_database   download the latest version of CheckV's database
    update_database     update CheckV's database with your own complete genomes

optional arguments:
  -h, --help  show this help message and exit
;

Dear @mijiandui 
Can you indicate which script was used to cluster virus ?

thanks a lot!

**Comment by mijiandui** [comment]
please find on the website: https://bitbucket.org/berkeleylab/checkv/src/master/
Supporting code
Rapid genome clustering based on pairwise ANI

First, create a blast+ database:
makeblastdb -in <my_seqs.fna> -dbtype nucl -out <my_db>

Next, use megablast from blast+ package to perform all-vs-all blastn of sequences:
blastn -query <my_seqs.fna> -db <my_db> -outfmt '6 std qlen slen' -max_target_seqs 10000 -o <my_blast.tsv> -num_threads 32

Next, calculate pairwise ANI by combining local alignments between sequence pairs:
anicalc.py -i <my_blast.tsv> -o <my_ani.tsv>

Finally, perform UCLUST-like clustering using the MIUVIG recommended-parameters (95% ANI + 85% AF):
aniclust.py --fna <my_seqs.fna> --ani <my_ani.tsv> --out <my_clusters.tsv> --min_ani 95 --min_tcov 85 --min_qcov 0

Thanks

**Comment by ChaoXianSen** [comment]
Dear @mijiandui

Thanks a lot, thank you !
